### ISSUE TITLE
[Question]: When running the dolphinscheduler docker there is the error from the docker's log -> java.sql.SQLException: Access denied for user 'root'@'localhost'

### ISSUE THREAD

**Issue by huanghuihui0904** [cubefs/compass#214]
### Contact Details

huihuihuang0904@gmail.com

### What would you like to ask or discuss?

In the compass.yml file I find that the password should be **Root@666** and I change that, but the error still exists.
![image](https://github.com/cubefs/compass/assets/71327352/0148d39e-040c-407b-9b51-33f294db5045)
I also change this, as in other file you use localhost not 127.0.0.1, but the error still exists.
![image](https://github.com/cubefs/compass/assets/71327352/a9dbec7f-9733-4e85-8bf8-26ccb0f2d177)
Also I search that it will be better that the password does't include special symbol, so I change it to other password, but the error still exist.
I will be very appreciate for your reply! Thank you!

**Comment by nilnon** [comment]
@huanghuihui0904 Sorry for replying so late. This seems to be a user permissions issue. You need to grant root access. Try running: `GRANT ALL ON *.* TO 'root'@'%'; FLUSH PRIVILEGES;` It may be caused by the failure of this line of command to be executed successfully, refer to [compass-playground-dolphinscheduler.Dockerfile](https://github.com/cubefs/compass/blob/main/docker/playground/dockerfiles/compass-playground-dolphinscheduler.Dockerfile#L70).  In addition, the args of dolphinscheduler in compose.yml have not been used in the dockerfile. If you are interested in optimizing it, welcome to submit a PR.

**Comment by huanghuihui0904** [comment]
Thank you for your reply! Then I use `docker-compose --profile dolphinscheduler up -d --build`  which adds `--build` to your provided instruction and finally solve the problem. 

However, I still have some problems and wonder whether the project has a Wehcat group or Feishu group for discussion?

**Comment by nilnon** [comment]
> Thank you for your reply! Then I use `docker-compose --profile dolphinscheduler up -d --build` which adds `--build` to your provided instruction and finally solve the problem.
> 
> However, I still have some problems and wonder whether the project has a Wehcat group or Feishu group for discussion?

@huanghuihui0904 If you still have questions related to the project, you can submit an issue directly, or send me an email.

**Comment by huanghuihui0904** [comment]
Thanks for your help!
